FROM ubuntu:20.04
COPY \client \client
WORKDIR \client
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install thrift
EXPOSE 8080
CMD [ "python3","clientCalculator.py" ]