#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Result; end

class Result
  include ::Thrift::Struct, ::Thrift::Struct_Union
  RESULT = 1
  ERROR = 2

  FIELDS = {
    RESULT => {:type => ::Thrift::Types::DOUBLE, :name => 'result'},
    ERROR => {:type => ::Thrift::Types::STRING, :name => 'error'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

